version: "3.9"

services:
  app:
    build: 
      args: 
        user: lucaspay
        uid: 1001
      context: ./.docker
      dockerfile: Dockerfile
    image: ms-notification
    container_name: notification-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes: 
      - ./src:/var/www
  nginx:
    image: nginx:1.19.9-alpine
    container_name: notification-nginx
    restart: unless-stopped
    ports: 
      - 8005:80
    depends_on: 
      - app
    volumes: 
      - ./src:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
