version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.9.4-management-alpine
    container_name: ms-queues
    ports: 
      - 5672:5672
      - 15672:15672
    volumes: 
      - ~/.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker/rabbitmq/log/:/var/log/rabbitmq